import React from "react";
import { createRoot } from "react-dom/client";
import { App } from "./App";
import "./styles.css";
import "./dashboard.css";
import "./aesthetic.css";
import "./clean.css";
import "./polish.css";
import "./fix.css";
import "./header-scroll.css";
import "./unified-theme.css";
import "./mobile.css";
import "./mobile-v07.css";
import "./nav-lock.css";
createRoot(document.getElementById("root")).render(<App />);
